[acbotics]
    path = /home/acbotics/Downloads/acbotics
    comment = acbotics download folder
    uid = acbotics
    gid = acbotics
    read only = no
    list = yes
    # secrets file
    auth users = acbotics
    secrets file = /etc/rsyncd.secrets
    hosts allow = 192.168.0.0/255.255.255.0, 192.168.1.0/255.255.255.0,
    192.168.9.0/255.255.0.0
